### ISSUE TITLE
Create .npmignore

### ISSUE THREAD

**Issue by ProbablePrime** [Lange/node-elgato-stream-deck#22]
We should exclude our fixtures and other junk from the npm release to drop file size

**Comment by Lange** [comment]
It should be possible to do this just via the `files` field in package.json.

**Comment by Lange** [comment]
Going to close this for now because I'm 99% sure that our exiting `files` field already ensures we're uploading the minimal set of files.

**Comment by ProbablePrime** [comment]
Yep you're right, run npm pack and check the tarbell :)

**Comment by Lange** [comment]
Ahh okay, yeah I was trying to figure out how to check that haha.
