### ISSUE TITLE
No executable, possible errors with project file

### ISSUE THREAD

**Issue by rolypolyman** [Lange/node-elgato-stream-deck#33]
I was gifted a Stream Deck and I have Windows 7.  Surprise, surprise, no support from the manufacturer for anything less than Windows 10.  One of the forums online suggested this as a solution.  However I am new to node.js and GitHub, and I am not understanding from the project description how this is supposed to work..

I did successfully install Node.js and npm, and installed windows-build-tools successfully.  I then tried running the elgato-stream-deck program.  Below is the capture of my install.  The problems I have are:

1. I am not seeing where any executable has been created, and nothing new in my start menu or desktop.  Isn't there supposed to be an app similar to the official Stream Deck app?  I don't know what to do to get my Stream Deck running and working with OBS Studio.

2. Why am I getting "no such file or directory, open 'C:\Windows\system32\package.json' " in the dump below?

Thanks.

___________________________________________
C:\Windows\system32>npm install elgato-stream-deck

> node-hid@0.5.7 install C:\Windows\system32\node_modules\node-hid
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.2
prebuild-install info looking for local prebuild @ prebuilds\node-hid-v0.5.7-node-v48-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\rec\AppData\Roaming\npm-cache\_prebuilds\https-github.com-node-hid-node-hid-releases-download-v0.5.
7-node-hid-v0.5.7-node-v48-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\rec\AppData\Roaming\npm-cache\_prebuilds\https-github.com-node-hid-node-hid-releases-download-v0.5.7-node-hid-v0.5.7-
node-v48-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Windows\system32\node_modules\node-hid\build\Release\HID.node
prebuild-install info unpack required C:\Windows\system32\node_modules\node-hid\build\Release\HID.node successfully
prebuild-install info install Successfully installed prebuilt binary!
C:\Windows\system32
`-- elgato-stream-deck@1.2.0
  `-- node-hid@0.5.7
    +-- bindings@1.3.0
    +-- nan@2.7.0
    `-- prebuild-install@2.2.2
      +-- expand-template@1.1.0
      +-- github-from-package@0.0.0
      +-- minimist@1.2.0
      +-- mkdirp@0.5.1
      | `-- minimist@0.0.8
      +-- node-abi@2.1.1
      +-- noop-logger@0.1.1
      +-- npmlog@4.1.2
      | +-- are-we-there-yet@1.1.4
      | | +-- delegates@1.0.0
      | | `-- readable-stream@2.3.3
      | |   +-- core-util-is@1.0.2
      | |   +-- inherits@2.0.3
      | |   +-- isarray@1.0.0
      | |   +-- process-nextick-args@1.0.7
      | |   +-- string_decoder@1.0.3
      | |   `-- util-deprecate@1.0.2
      | +-- console-control-strings@1.1.0
      | +-- gauge@2.7.4
      | | +-- aproba@1.1.2
      | | +-- has-unicode@2.0.1
      | | +-- object-assign@4.1.1
      | | +-- signal-exit@3.0.2
      | | +-- string-width@1.0.2
      | | | +-- code-point-at@1.1.0
      | | | `-- is-fullwidth-code-point@1.0.0
      | | |   `-- number-is-nan@1.0.1
      | | +-- strip-ansi@3.0.1
      | | | `-- ansi-regex@2.1.1
      | | `-- wide-align@1.1.2
      | `-- set-blocking@2.0.0
      +-- os-homedir@1.0.2
      +-- pump@1.0.2
      | +-- end-of-stream@1.4.0
      | `-- once@1.4.0
      |   `-- wrappy@1.0.2
      +-- rc@1.2.1
      | +-- deep-extend@0.4.2
      | +-- ini@1.3.4
      | `-- strip-json-comments@2.0.1
      +-- simple-get@1.4.3
      | `-- unzip-response@1.0.2
      +-- tar-fs@1.15.3
      | +-- chownr@1.0.1
      | `-- tar-stream@1.5.4
      |   `-- bl@1.2.1
      +-- tunnel-agent@0.6.0
      | `-- safe-buffer@5.1.1
      `-- xtend@4.0.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

C:\Windows\system32>

**Comment by Lange** [comment]
Hi @rolypolyman,

It seems you may have misunderstood the purpose of this library and how Node.js and npm work in general.

`node-elgato-stream-deck` is not an application. It's not a program you run that gives you an alternate UI for interacting with the Stream Deck. It's a library that developers can use to _make_ custom applications that interact with the Stream Deck.
