### ISSUE TITLE
Consider returning the StreamDeck class, rather than an automatically-constructed instance of it

### ISSUE THREAD

**Issue by Lange** [Lange/node-elgato-stream-deck#35]
The time has finally come for me to use this library in a real project, and I'm immediately seeing a fairly substantial flaw in the current release.

Our current code tries to be helpful by automatically finding the first connected Stream Deck and constructing an instance of the `StreamDeck` class around it. However, this completely prevents consumers of this package from ever implementing their own reconnect logic, or from implementing support for multiple connected Stream Decks.

Long-term, something like PR #27 will fix this. Short-term, I propose that we simply stop trying to automatically-construct an instance of the StreamDeck class, and instead just expose the class itself. The responsibility of finding the device path and passing it to the constructor would then fall to the consumer of this package.

This would be a breaking change, and would also require some documentation updates. I can get this work done quickly, but I wanted to get some quick input from others before I went ahead and did so.

**Comment by Lange** [comment]
@ProbablePrime Whoops, didn't mean to assign you! I did however, mean to ping you so that you could offer your input.

**Comment by ProbablePrime** [comment]
This does make sense yes. We could potentially write things in such a way that node-hid could be swapped out this way too. 

The streamdeck class could take an interface that just has read, write and whatever else we need. 

On the documentation front we'd absoloutely need an example on a simple use case of one streamdeck etc.

Sounds great!

**Comment by ProbablePrime** [comment]
A lot of this already happened in: https://github.com/Lange/node-elgato-stream-deck/pull/28

I merged this into a branch as the author and I couldn't figure out why the tests on this branch fail. It was on my todo list to look into fixing and then to re-PR that branch into master. 

We should evaluate if that branch still has value and cherry pick across any functionality we'd like to retain

**Comment by Lange** [comment]
Aha! I thought this all sounded familiar.

I'll work on the `next` branch and try to get it ready to merge. I'm okay with using `jimp` instead of `sharp`, at least until `sharp` offers prebuilt binaries (which is actively being looked into).

**Comment by Lange** [comment]
Done, v2.0.0 released.
