### ISSUE TITLE
Rectangular images are not cropped and cannot be loaded to buttons

### ISSUE THREAD

**Issue by silid** [Lange/node-elgato-stream-deck#37]
The commit 5f47d7d030e2c05364a296cea117ce267ea1c37e removed the second argument from the sharp resize function. The second argument is required or the image isn't cropped and is the wrong aspect if not already square..

This commit should be reversed.

**Comment by Lange** [comment]
This will be fixed in #36

**Comment by Lange** [comment]
Fixed!
