### ISSUE TITLE
Avoid double hitting a key

### ISSUE THREAD

**Issue by silid** [Lange/node-elgato-stream-deck#38]
I've noticed on my stream deck that sometimes it registers as two clicks when I press or release a button.
Eg. when pressing down it may log a Down-Up-Down in quick succession, or when releasing a key it may log an Up-Down-Up.

Do any of you have good suggestions for mitigating this?

**Comment by Lange** [comment]
Use a debouncer in your event handlers, such as [lodash.debounce](https://www.npmjs.com/package/lodash.debounce).

**Comment by Lange** [comment]
Closing, as this is something which can and should be handled via a separate debouncer. Feel free to comment again if you need additional guidance though!
