### ISSUE TITLE
Key display issue

### ISSUE THREAD

**Issue by freelancer42** [Lange/node-elgato-stream-deck#40]
I've been using this library with my stream deck successfully for the past few days, but ran into an issue today. All the keys seem to have a kind of grey "overlay" that makes the image look kinda blurry and washed out. Even the empty keys are now grey rather than black.

I've tried unplugging the stream deck and plugging it back in, and also tried connecting it to another computer that has the official software installed, but the issue persists. Prior to this I've only used the stream deck with this node library (I only bought it a few days ago), so it kinda seems like it wrote something to the device that it didn't like.

Has anyone else seen this issue before? Any idea what to do?

**Comment by Lange** [comment]
Interesting, this is the first I've heard of this issue. The only thing I can think of would be to check the brightness setting of the device, though I don't think that would cause issues like what you're describing.

**Comment by freelancer42** [comment]
Yeah it's not the brightness setting. Turning it up definitely makes it worse though (or rather, more apparent). It really seems like a semi-transparent grey box is overlayed on top of the keys.

**Comment by Lange** [comment]
At this time I've no idea what the cause of this issue could be, so I'm afraid I can't offer any assistance. Please keep us in the loop with any further findings you have though.

**Comment by jesperstarkar** [comment]
Posting an image might help?

**Comment by freelancer42** [comment]
It's a little bit hard to get a good photo of it, but this is the stream deck connected to the official app with the default template (just an icon in the middle) at the lowest brightness setting:

![img_20171216_101309](https://user-images.githubusercontent.com/16519229/34094225-9435d8c8-e3cc-11e7-9a3e-63f4ac939bc8.jpg)

And this is at the highest setting:

![img_20171216_101331](https://user-images.githubusercontent.com/16519229/34094226-98620e62-e3cc-11e7-9d2a-d41b33b5fc74.jpg)

**Comment by freelancer42** [comment]
I've been in contact with Elgato support. Their best guess is that it's a hardware issue, so I'm gonna try to get the unit replaced. I'll let you know if there's any issues with the new unit when I get it.

**Comment by Lange** [comment]
@freelancer42 Any updates? Are we okay to close this issue?

**Comment by freelancer42** [comment]
My apologies, I could've sworn I already posted this, but yeah the new unit is working fine and doing very well with the library for a month and a half now.

**Comment by Lange** [comment]
Wonderful news! Thanks for the closure :+1:
