### ISSUE TITLE
How to allow user use Stram Deck on Raspbian

### ISSUE THREAD

**Issue by norfair00** [Lange/node-elgato-stream-deck#41]
Hello,

On run node script for Stream Deck i have this error `Error: cannot open device with path 0001:0004:00`

**Comment by Lange** [comment]
Hi @norfair00,

Hm, I didn't encounter this issue when I did initial testing of this library on my Raspberry Pi 3. I unfortunately don't have time to look into this myself right now; maybe someone else can offer some insight?

**Comment by uffefrostbox** [comment]
Hi. I have the same problem. @norfair00 Did you find a way to fix this? Thanks in advance

**Comment by DGivney** [comment]
I get the same error on Ubuntu 16.04.

Running the command with sudo works however; **sudo node rapid-fill.js**

**Comment by uffefrostbox** [comment]
Thanks you @DGivney ! It works on my setup now when I run the examples with sudo. I.e Raspbian on RPi3 with stream deck firmware 1.0.170133. I very much appriciat both your support and Langes amazing job creating this API! Thanks

**Comment by DGivney** [comment]
@uffefrostbox The permissions are set by the OS on 'input' devices to prevent key-loggers etc from accessing your keyboard commands.  I was able to fix this issue with a udev rule however.

See the installation script on this project which creates a udev rule on a Raspberry Pi;
https://github.com/abcminiuser/python-elgato-streamdeck#user-content-raspberry-pi-installation

The rule I needed for Ubuntu was slightly different;
**/etc/udev/rules.d/95-stream-deck.rules**
`SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"`

After a restart it is now working.

**Comment by Julusian** [comment]
I assume this was resolved. I expect that the udev rule was the problem, I am adding a section to the README to specify that will need to be done on linux
