### ISSUE TITLE
Check if things still work against the latest Stream Deck firmware

### ISSUE THREAD

**Issue by Lange** [Lange/node-elgato-stream-deck#42]
I haven't had a chance to try out the current firmware -- can anyone confirm if this library still works as expected with it? Thanks!

**Comment by ProbablePrime** [comment]
On it :)

**Comment by ProbablePrime** [comment]
@Lange All the example files we have work :)

**Comment by Lange** [comment]
@ProbablePrime awesome, thank you so much for testing!
