### ISSUE TITLE
Get Firmware Version and Serial Number

### ISSUE THREAD

**Issue by PimHaarsma** [Lange/node-elgato-stream-deck#45]
Hello,

I missed the function to obtain version number and serial number from the Stream Deck, which does have the original software. I figured it out, and this works on my Stream Deck:
(Currently I can't do a pull request, but here is the code) 😃 

	/**
	 * Get firmware version from Stream Deck
	 */
	getFirmwareVersion() {
		return this.device.getFeatureReport(4, 17).slice(5).map(function(val){
			return String.fromCharCode(val);
		}).join('');
	}
	
	/**
	 * Get serial number from Stream Deck
	 */
	getSerialNumber() {
		return this.device.getFeatureReport(3, 17).slice(5).map(function(val){
			return String.fromCharCode(val);
		}).join('');
	}

**Comment by Lange** [comment]
Nice, thanks for this! I'm a bit busy currently so you might be able to get around to opening a PR before I can.

**Comment by Julusian** [comment]
This has been done and will be in the next release
