### ISSUE TITLE
How are you snooping communication?

### ISSUE THREAD

**Issue by wuest** [Lange/node-elgato-stream-deck#47]
In https://github.com/Lange/node-elgato-stream-deck/blob/master/NOTES.md you note that the Stream Deck software sends specific messages at initialization.

Was this guesswork, or do you have a method to snoop the communication?

I ask because I noticed that out of the box, the device info from my Stream Deck via Haskell's `System.HIDAPI` reported that the serial number was `Just ""` - whereas after plugging the Stream Deck into a Windows box and running Elgato's software, the serial number is populated.  This tells me that some manner of one-time communication is occurring and I'd LOVE to be able to snoop on it.

**Comment by Lange** [comment]
I personally used [WireShark](https://www.wireshark.org/), which happens to have support for capturing USB packets in addition to network packets.

This page should hopefully be helpful in getting that up and running: https://wiki.wireshark.org/CaptureSetup/USB

**Comment by wuest** [comment]
Oh nice!  I'm so used to using `tcpdump` and just using WireShark to view the pcap, that I had no idea it had USB capture support.

I'll hopefully have some additional documentation to add to your notes after this weekend.
