### ISSUE TITLE
Questions about purpose

### ISSUE THREAD

**Issue by asdf23** [Lange/node-elgato-stream-deck#50]
Forgive me if this is the wrong place to ask..

I've not quite wrapped by head around the purpose of this project. Is the purpose to replace the stream deck software? (Or do both work together?) I understand that installation the stream deck software is a requirement for this software - but does it need to be running?  If it is a replacement then would that mean that I lose the screen timeout and folder functionality?

What I was hoping that with this software was a couple of things that the out-of-the-box software cannot do. Specifically:

1. Change button images and functionality dynamically (meaning... on the click of a button I want to launch a program, and then reset the button to a disabled state. In the disabled state another button click would be ignored.
2. Display a status (meaning... every few seconds some program I would write would change the button to display a status [CPU temperature perhaps])
3. Move the position of the up-one-folder button (or change it to a set of buttons that can cycle through different modes)
4. Change the display based on a custom event fired from some software I would write

I hope that makes since. Thank you!

**Comment by Lange** [comment]
Hi there,

This is a common question. You can find the answer you're looking for right at the top of our [README](https://github.com/Lange/node-elgato-stream-deck/blob/master/README.md):

> ❗ Please note that `node-elgato-stream-deck` is NOT a standalone application. It is not something you download and run on its own. It is not an alternative to the [official Stream Deck program provided by Elgato](https://www.elgato.com/en/gaming/downloads). Instead, `node-elgato-stream-deck` is a code library, which developers can use to make their own applications which interface with the Stream Deck.

**Comment by Lange** [comment]
I've [updated the README](https://github.com/Lange/node-elgato-stream-deck/commit/2b979931c81736daa8469b603795d7abc7d8d377) to further clarify this, as it seems like a number of people are finding this library on google and mistakenly thinking it is a standalone replacement for the official Stream Desk software.

I apologize for any frustration you may have experienced while figuring out what this library is and is not. If it's any consolation, you are not the first person to have this happen:

- https://github.com/Lange/node-elgato-stream-deck/issues/44
- https://github.com/Lange/node-elgato-stream-deck/issues/33
