### ISSUE TITLE
Key Display Issue

### ISSUE THREAD

**Issue by heytreylive** [Lange/node-elgato-stream-deck#52]
Just bought a new Stream Deck unit. First day the keys were working fine, but this morning the keys looked milky/grayed out. The keys still work but the display has the issue. 
![31699021_10155551065508494_2177487099823915008_n](https://user-images.githubusercontent.com/38894302/39493568-537a58dc-4d61-11e8-9705-57c1e30c049e.jpg)

**Comment by Lange** [comment]
Is this only happening when using this library? If it also happens when using the first-party Stream Deck software, then it may be a hardware issue. You would need to contact Elgato's customer support, in that case.

**Comment by Lange** [comment]
To clarify: we are not Elgato, this is a community-made code library providing a JavaScript API for the Stream Deck. We will be unable to assist with hardware issues or provide customer support.

You can find Elgato's help portal here: https://gaming.help.elgato.com/customer/en/portal/articles

**Comment by heytreylive** [comment]
ya i just figured i'd look to see if anyone knew of a solution before i went to them. Thanks man. its definitely a hardware issue. i'll just go to them thanks.
