### ISSUE TITLE
Thanks for the Notes :-)

### ISSUE THREAD

**Issue by Coffee2CodeNL** [Lange/node-elgato-stream-deck#53]
Thanks to your notes I had a notion of what to look for in the USB packets :+1: 

Now there's an alternative to Elgato's own Stream Deck software being developed :grin: 

See: https://git.coffeenet.nl/Coffee2Code/LinGato

I've also featured you on my blog: https://coffee2code.space/2018/07/04/alternative-elgato-stream-deck-software.html

**Comment by Lange** [comment]
Happy to have been of assistance!
