### ISSUE TITLE
Node 10 support? | error: no matching member function for call to 'NewInstance'

### ISSUE THREAD

**Issue by lc-101** [Lange/node-elgato-stream-deck#58]
Hello everyone, 
I had noticed that I was getting errors during install when node-hid was getting installed. 
```
"error: no matching member function for call to 'NewInstance' 
Local<Object> buf = nodeBufConstructor->NewInstance(1, nodeBufferArgs);"
```

It seems node-hid is using some deprecated node APIs not comparable with node v10
https://github.com/node-hid/node-hid/issues/266

This has been corrected in node-hid 7.3. I did a test with the newer version of node-hid and it seems to work well with the node-elgato-stream-deck API and node v10+

**Comment by Lange** [comment]
Hi @lc-101,

Please see https://github.com/Lange/node-elgato-stream-deck/pull/51 for more information. I agree we should support Node 10, but Linux support is the blocker right now.

**Comment by jpoppe** [comment]
Just got my Stream Deck and made it working with node 10 and Linux, you could rebuild node-hid, with the following command to use the libusb driver:

cd node_modules/node-hid node-gyp rebuild --driver=libusb

Or on installation:
npm_config_build_from_source=true npm_config_driver=libusb yarn add node-hid
npm install node-hid --build-from-source --driver=libusb

(took me a while to figure out the yarn translation :stuck_out_tongue: 

Resources: https://github.com/node-hid/node-hid#selecting-driver-type

**Comment by Julusian** [comment]
v3.0.0 has just been published which will resolve this issue
