### ISSUE TITLE
NPM package contains no typings

### ISSUE THREAD

**Issue by Llorx** [Lange/node-elgato-stream-deck#59]
![image](https://user-images.githubusercontent.com/702490/45001261-f8ab5500-afcb-11e8-8564-fa97e1e630d6.png)

Easy as that.

**Comment by Llorx** [comment]
You have the typings right there in GitHub, but not pushed them to the npm package.

**Comment by Julusian** [comment]
The next release will resolve this

**Comment by Julusian** [comment]
v3.0.0 has just been published
