### ISSUE TITLE
Support adding text labels to buttons

### ISSUE THREAD

**Issue by Lange** [Lange/node-elgato-stream-deck#6]
The official Elgato Stream Deck software renders text by just baking it into the bitmap that it sends. We'll need to replicate this behavior.

**Comment by Lange** [comment]
[`node-canvas`](https://github.com/Automattic/node-canvas) might be a good lib to use for this. A cursory search did not reveal any viable alternatives.

**Comment by Lange** [comment]
[`gm`](https://www.npmjs.com/package/gm) seems to suffer from the same problems as node-canvas, in that it requires the user to install third-party apps separately.

[`node-gd`](https://www.npmjs.com/package/node-gd) does not work on Windows.

**Comment by ProbablePrime** [comment]
We could potentially add full drawing capabilities. Or some templates too. The twitch viewer number from the original software was interesting.

**Comment by danieltian** [comment]
I found this, though I haven't tested it to see how well it works:

https://www.npmjs.com/package/pureimage

Only JS dependencies, no external deps.

**Comment by Lange** [comment]
Oooh awesome find @danieltian! I think that `pureimage` is our best choice as of right now.

**Comment by Lange** [comment]
I've tried out `pureimage` and I was indeed able to get it working. However, it's not really that great at drawing text yet, but it's better than nothing.

![img_20170519_001358](https://cloud.githubusercontent.com/assets/873012/26234271/19ef2efc-3c29-11e7-854c-1346ec06fbdf.jpg)

I have committed the code that generated this to [`examples/text-generation.js`](https://github.com/Lange/node-elgato-stream-deck/blob/master/examples/text-generation.js). There is a _lot_ of room to make this better before we turn it into a proper API method, so help is welcome!

**Comment by danieltian** [comment]
Nice! It looks awesome! That should be good enough for now, I suspect that most people would be using bitmaps anyhow with on-the-fly text rendering as a niche case. Perhaps the feature can be expanded out in the future to allow for on-the-fly drawing of basic shapes, including text.

**Comment by paul-lrr** [comment]
I was messing around with the *sharp* library that you are already using for `fillImageFromFile` and noticed that it can composite SVG files as well as the bitmap graphics. By doing something like
```javascript
let textSVG = `<svg width="72px" height="72px" viewBox="0 0 72 72">
<text x="5" y="70" style="fill:red;">FOOBAR</text>
</svg>`;
image.overlayWith(new Buffer(textSVG))
```
You can create an SVG document and overlay it on an existing *sharp* image. The nice thing is that you automatically get all the fonts, colors, styling, etc that you can do in regular SVG files. It seems like this same technique could also be used for basic shape drawing as mentioned above.

*btw: thanks for working on this API so quickly after the release of the Stream Deck. It really opens up all sorts of cool possibilities for this little thing!*

**Comment by Lange** [comment]
Of course! That's brilliant @paul-lrr! We should absolutely take that route.

**Comment by paul-lrr** [comment]
So I wrinkle that I have encountered with the SVG plan is that, since you can't easily parse a real SVG document in node (without a browser to render it), anything fancy you want to do, like text wrapping or custom fonts, is difficult.  I think I have a solution for text wrapping by using *[opentype.js](https://github.com/nodebox/opentype.js/)* to measure the text directly to set the line breaks, but it is a bit of a hack 😕

**Comment by Lange** [comment]
The existing Elgato software doesn't seem to support line breaks either, so
I'd be okay with that limitation. I'd view line breaks as an awesome extra
feature.

Likewise for fonts -- the Elgato software just supports the one default
font. Us supporting multiple fonts would be going above and beyond.

**Comment by hedgehog1029** [comment]
could potentially look at [jimp](https://www.npmjs.com/package/jimp) - it supports text w/ wrapping, though it can only load a format called "BMFont" (tools to convert TTFs exist apparently). another benefit of jimp is that it has zero native dependencies, which makes this library more portable.

**Comment by Julusian** [comment]
I expect that trying to provide text rendering will become a nightmare to maintain as everyone will want it to be done slightly differently.
And with sharp now removed as a dependency, doing any text rendering no longer belongs in this project. 
There is an example in the project to give users a starting point for doing it themselves, perhaps that is enough?
