### ISSUE TITLE
SDK release

### ISSUE THREAD

**Issue by CeH9** [Lange/node-elgato-stream-deck#63]
Finally they did it, great news! [link](https://gaming.help.elgato.com/customer/en/portal/articles/2965624-elgato-stream-deck-sdk-%E2%80%93-use-software-version-4-0-and-above)

**Comment by joeygallegos** [comment]
I love it! I hope somebody makes the Stream Deck into a launchpad! haha. [`https://youtu.be/y04W3RFKxwk?t=8`](https://youtu.be/y04W3RFKxwk?t=8)

**Comment by n-scope** [comment]
AFAIK they still dont support linux. So I hope this repo will stay alive

**Comment by Lange** [comment]
I admit that I am not currently using this library in any projects. As a result, I am unable to dedicate time towards maintaining it. Maintenance PRs welcome.

**Comment by Julusian** [comment]
The SDK is for writing actions to be used in their control software, so isn't really relevant to this library. Especially as they do not support linux.
