### ISSUE TITLE
Gif support?

### ISSUE THREAD

**Issue by Hugobox** [Lange/node-elgato-stream-deck#75]
Hi!
I've seen that the latest steam-deck 3.0 now supports gif, does your library also support it? If not, are you planning on implementing it?
Thanks for the consideration!

**Comment by Julusian** [comment]
This library doesnt support any specific image formats. All it does is to transfer a raw pixel buffer to the device. There are no current plans to add back any support for handling encoded images.

It is up to you the users of the api to decode and manipulate any images into a Buffer before passing them to the api. So you can do animated gifs or similar by calling the api with each frame at the correct interval for the animation.
