### ISSUE TITLE
New revision of stream deck released which does not work

### ISSUE THREAD

**Issue by uffefrostbox** [Lange/node-elgato-stream-deck#76]
Hi
I have a user that cannot get my software to connect with his Stream Deck and it seems that there have been a silent release of a new revision that breaks compatibility with this library and that these units are now getting into the wild.

I have not had a changes to get hands on with the new revision to do further testing. I know that the Companion Slack group is working on a fix for Companion right now. They referred to this document https://www.elgato.com/sites/default/files/inline-files/Elgato_Stream_Deck_Declaration_of_Conformity_20190903_0.pdf
in which they now referrer to two model numbers 20GAA9901; 20GAA9902 the later one being the new revision.

Anyone else having these issues?

**Comment by Julusian** [comment]
Hi
Yes, I am following along with Companion too (Related: https://github.com/bitfocus/companion/issues/886).
It would appear that the protocol has changed, so someone needs to spend some time with one to figure out the protocol changes then it can be fixed in both this library and Companion

**Comment by Julusian** [comment]
Companion hope to have working support in about a week. Once they have done so I shall port that code back into this library. It'll be a bit hard to test, and will likely involve some trial and error (based on when how the mini support went), but hopefully it won't be very painful

**Comment by Julusian** [comment]
This should work now in v3.2.0 of the library
