### ISSUE TITLE
Cancel Existing action in button ?

### ISSUE THREAD

**Issue by chf17** [Lange/node-elgato-stream-deck#82]
How to cancel existing action on each button ?

Example, when my PC start, streamDeck official application load profile and affet icon et action on each button. But when a change with API , icon and action on buttons, on press two action is launched  : My Action and action profile

**Comment by Julusian** [comment]
Due to the way the streamdeck works, there is nothing we can do on this.
The only way to stop this from happening is to only run one program which interacts with the streamdeck at a time
