### ISSUE TITLE
Node-hid dependecy update because of prebuilds for node 14

### ISSUE THREAD

**Issue by askeron** [Lange/node-elgato-stream-deck#85]
There is a new version of node-hid (1.3.0 instead of the currently used 1.2.0). It has a bugfix, but more important it has prebuilds for node 14, which 1.2.0 does not have. Therefor it would be really nice to have this dependency update.

**Comment by askeron** [comment]
Sorry, I just saw that node-hid has a 1.3.0 release on github, but on npm it is still 1.2.0. I opened an issue (https://github.com/node-hid/node-hid/issues/377) and will reply here, when the version is finally on npm.

**Comment by Julusian** [comment]
There isn't anything this library needs to do to support this. npm will install and use node-hid 1.3.0 once it is published.
You will just need to do a `npm upgrade` or something to update the child-dependencies you have in your package-lock.json

**Comment by askeron** [comment]
Sorry, my mistake. Best Regards
